Pandas is an open sourse, providing high performance, easy to use data structures for the Python programming.

Various Operations in Pandas

firstly we will import Pandas and Numpy libraries as follows 

In [1]:
import numpy as np 
import pandas as pd # data processing

Lets create a DataFrame 

In [2]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=['Row1', 'Row2','Row3','Row4','Row5'], columns=['Column1','Column2','Column3','Column4'])

In [3]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

you can change a Dataframe to a CSV file as follows 

In [4]:
df.to_csv('Test1.csv')

How to access the elements in a dataframe?

1th way is .loc

2th way is .iloc

In [5]:
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [6]:
type(df.loc['Row1'])

pandas.core.series.Series

In [7]:
df.iloc[:,:]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [8]:
df.iloc[0:2,0:2]

Column1  Column2
Row1        0        1
Row2        4        5

In [9]:
type(df.iloc[0:2,0:2])

pandas.core.frame.DataFrame

In [10]:
df.iloc[0:2,0:1]

Column1
Row1        0
Row2        4

In [11]:
type(df.iloc[0:2,0:1])

pandas.core.frame.DataFrame

Lets choose the elements from column2 

In [12]:
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

How to convert a DataFrame into arrays?


In [13]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [14]:
df.iloc[:,1:].values.shape

(5, 3)

In [15]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [16]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [17]:
df['Column1'].value_counts()

12    1
4     1
16    1
8     1
0     1
Name: Column1, dtype: int64

In [18]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

In [19]:
df['Column3']

Row1     2
Row2     6
Row3    10
Row4    14
Row5    18
Name: Column3, dtype: int64

In [20]:
type(df['Column3'])

pandas.core.series.Series

In [21]:
df[['Column3','Column4']]

Column3  Column4
Row1        2        3
Row2        6        7
Row3       10       11
Row4       14       15
Row5       18       19

In [22]:
df=pd.read_csv('../input/mercedesbenz-greener-manufacturing/train.csv')

In [23]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [25]:
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

GET THE UNIQUE CATEGORY COUNTS LIKE THIS;

In [26]:
df['X10'].value_counts()

0    4153
1      56
Name: X10, dtype: int64

In [27]:
df['X10'].unique()

array([0, 1])

In [28]:
df[df['y']>120]

ID       y  X0  X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k   v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al   r   e  f  d   f  h  s  ...     0     0     0     0   
9       30  126.99   j   b  aq  c  d   f  a  e  ...     0     0     1     0   
23      52  120.77   x   b   m  c  d   j  j  n  ...     0     0     1     0   
29      67  128.19   x   b   m  c  d   j  j  n  ...     0     0     1     0   
...    ...     ...  ..  ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4043  8104  125.10   x  aa  as  c  d   w  h  a  ...     1     0     0     0   
4069  8151  121.65  ap   l   s  c  d   w  h  l  ...     0     0     0     0   
4176  8344  149.52  ak   l  as  a  d  aa  j  r  ...     0     0     1     0   
4186  8371  131.98   j   f  ar  a  d  aa  j  n  ...     0     0     1     0   
4202  8402  123.34  ap   l   s  c  d  aa  d  r  ...     0     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
9        0     0     0     0     0     0  
23       0     0     0     0     0     0  
29       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4043     0     0     0     0     0     0  
4069     0     0     0     0     0     0  
4176     0     0     0     0     0     0  
4186     0     0     0     0     0     0  
4202     0     0     0     0     0     0  

[220 rows x 378 columns]

In [29]:
df[df['ID']<20]

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   
5  18   92.93   t  b   e  c  d  g  h  s  ...     0     0     1     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  
5     0     0     0     0     0  

[6 rows x 378 columns]

In [30]:
from io import StringIO,BytesIO

In [31]:
data=('col1,col2,col3\n'
         'x,y,1\n'
         'a,b,2\n'
         'c,d,3')

In [32]:
type(data)

str

In [33]:
StringIO()

In [34]:
df=pd.read_csv(StringIO(data))

In [35]:
df

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

READ FROM SPECIFIC COLUMNS AS FOLLOWS

In [36]:
df=pd.read_csv(StringIO(data), usecols=['col1','col3'])

In [37]:
df

col1  col3
0    x     1
1    a     2
2    c     3

In [38]:
df = pd.read_csv(StringIO(data), usecols=['col2','col3'])

In [39]:
df

col2  col3
0    y     1
1    b     2
2    d     3

SPECIFYING COLUMNS OF DATA TYPES

In [40]:
data=('a,b,c,d\n'
         '1,2,3,4\n'
         '5,6,7,8\n'
         '9,10,11')

In [41]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11


In [42]:
pd.read_csv(StringIO(data))

a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN